.TH "colors" 3 "Version 1.0.0" "WallhavenAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colors \- Color macros
.PP
 \- Defining the hex values for the colors\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRosewood\fP   '660000'"
.br
.RI "Name for the color hex 660000\&. "
.ti -1c
.RI "#define \fBCrimsonRed\fP   '990000'"
.br
.RI "Name for the color hex 990000\&. "
.ti -1c
.RI "#define \fBRossoCorsa\fP   'cc0000'"
.br
.RI "Name for the color hex cc0000\&. "
.ti -1c
.RI "#define \fBPersianRed\fP   'cc3333'"
.br
.RI "Name for the color hex cc3333\&. "
.ti -1c
.RI "#define \fBDarkPink\fP   'ea4c88'"
.br
.RI "Name for the color hex ea4c88\&. "
.ti -1c
.RI "#define \fBWarmPurple\fP   '993399'"
.br
.RI "Name for the color hex 993399\&. "
.ti -1c
.RI "#define \fBEminence\fP   '663399'"
.br
.RI "Name for the color hex 663399\&. "
.ti -1c
.RI "#define \fBBlueberry\fP   '333399'"
.br
.RI "Name for the color hex 333399\&. "
.ti -1c
.RI "#define \fBScienceBlue\fP   '0066cc'"
.br
.RI "Name for the color hex 0066cc\&. "
.ti -1c
.RI "#define \fBPacificBlue\fP   '0099cc'"
.br
.RI "Name for the color hex 0099cc\&. "
.ti -1c
.RI "#define \fBDowny\fP   '66cccc'"
.br
.RI "Name for the color hex 66cccc\&. "
.ti -1c
.RI "#define \fBAppleGreen\fP   '77cc33'"
.br
.RI "Name for the color hex 77cc33\&. "
.ti -1c
.RI "#define \fBVenomGreen\fP   '669900'"
.br
.RI "Name for the color hex 669900\&. "
.ti -1c
.RI "#define \fBGreenLeaf\fP   '336600'"
.br
.RI "Name for the color hex 336600\&. "
.ti -1c
.RI "#define \fBGreenyBrown\fP   '666600'"
.br
.RI "Name for the color hex 666600\&. "
.ti -1c
.RI "#define \fBBrownYellow\fP   '999900'"
.br
.RI "Name for the color hex 999900\&. "
.ti -1c
.RI "#define \fBBirdFlower\fP   'cccc33'"
.br
.RI "Name for the color hex cccc33\&. "
.ti -1c
.RI "#define \fBArtyClickYellow\fP   'ffff00'"
.br
.RI "Name for the color hex ffff00\&. "
.ti -1c
.RI "#define \fBSunglow\fP   'ffcc33'"
.br
.RI "Name for the color hex ffcc33\&. "
.ti -1c
.RI "#define \fBOrangePeel\fP   'ff9900'"
.br
.RI "Name for the color hex ff9900\&. "
.ti -1c
.RI "#define \fBBlazeOrange\fP   'ff6600'"
.br
.RI "Name for the color hex ff6600\&. "
.ti -1c
.RI "#define \fBTerraCotta\fP   'cc6633'"
.br
.RI "Name for the color hex cc6633\&. "
.ti -1c
.RI "#define \fBWood\fP   '996633'"
.br
.RI "Name for the color hex 996633\&. "
.ti -1c
.RI "#define \fBNutmegWood\fP   '663300'"
.br
.RI "Name for the color hex 663300\&. "
.ti -1c
.RI "#define \fBBlack\fP   '000000'"
.br
.RI "Name for the color hex 000000\&. "
.ti -1c
.RI "#define \fBLemonGrass\fP   '999999'"
.br
.RI "Name for the color hex 999999\&. "
.ti -1c
.RI "#define \fBPastelGrey\fP   'cccccc'"
.br
.RI "Name for the color hex cccccc\&. "
.ti -1c
.RI "#define \fBWhite\fP   'ffffff'"
.br
.RI "Name for the color hex ffffff\&. "
.ti -1c
.RI "#define \fBGunPowder\fP   '424153'"
.br
.RI "Name for the color hex 424153\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defining the hex values for the colors\&. 

Color names are taken from from \fRArtyClick Colors\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for WallhavenAPI from the source code\&.
