.TH "Response" 3 "Version 1.0.0" "WallhavenAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Response \- Structure to store the response\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <wallhavenapi\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBvalue\fP"
.br
.RI "response string "
.ti -1c
.RI "size_t \fBsize\fP"
.br
.RI "size of the value "
.in -1c
.SH "Detailed Description"
.PP 
Structure to store the response\&. 


.PP
\fBNote\fP
.RS 4
Functions are not provided to maintain this struct\&. User have to manually handle the memory\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBparameters\&.c\fP, and \fBresponse\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WallhavenAPI from the source code\&.
